export const emptyTotals = {
  filtered: {
    SubTotalMXN: 0,
    NetoMXN: 0,
    TrasladosIVAMXN: 0,
    TrasladosIEPSMXN: 0,
    TrasladosISRMXN: 0,
    RetencionesIVAMXN: 0,
    RetencionesIEPSMXN: 0,
    RetencionesISRMXN: 0,
    count: 0,
    ImpuestosRetenidos: 0,
    DescuentoMXN: 0,
    Total: 0,
    TotalMXN: 0,
  },
  excercise: {
    SubTotalMXN: 0,
    NetoMXN: 0,
    TrasladosIVAMXN: 0,
    TrasladosIEPSMXN: 0,
    TrasladosISRMXN: 0,
    RetencionesIVAMXN: 0,
    RetencionesIEPSMXN: 0,
    RetencionesISRMXN: 0,
    count: 0,
    ImpuestosRetenidos: 0,
    DescuentoMXN: 0,
    Total: 0,
    TotalMXN: 0,
  },
};
