import { InternalTabType, TabType } from "../_types/ISRTypes";
import { getTableTabSwitchCondition } from "./getISRConditions";

export function getFieldsISRDeductions(tab: TabType, internalTab: InternalTabType) {
  const switchTab = getTableTabSwitchCondition(tab, internalTab);

  const COMMON_COLUMNS: Record<string, Record<string, string>> = {
    CASH: {
      Fecha: "Fecha expedición",
      UUID: "UUID",
      Serie: "Serie",
      Folio: "Folio",
      RfcEmisor: "RFC emisor",
      NombreEmisor: "Emisor",
      TipoDeComprobante: "Tipo de comprobante",
      UsoCFDIReceptor: "Uso de CFDI",
      "c_forma_pago.code": "Forma de pago código",
      "c_forma_pago.name": "Forma de pago",
      MetodoPago: "Método de pago",
      SubTotalMXN: "Subtotal",
      DescuentoMXN: "Descuentos",
      NetoMXN: "Neto",
      RetencionesISRMXN: "Retenciones ISR",
    },
    "DISCOUNTS-INCOMES": {
      Fecha: "Fecha expedición",
      UUID: "UUID",
      Serie: "Serie",
      Folio: "Folio",
      RfcReceptor: "RFC receptor",
      NombreReceptor: "Receptor",
      TipoDeComprobante: "Tipo de comprobante",
      UsoCFDIReceptor: "Uso de CFDI",
      "c_forma_pago.code": "Forma de pago código",
      "c_forma_pago.name": "Forma de pago",
      MetodoPago: "Método de pago",
      SubTotalMXN: "Subtotal",
      DescuentoMXN: "Descuentos",
      NetoMXN: "Neto",
    },
    "DISCOUNTS-EGRESS": {
      Fecha: "Fecha expedición",
      UUID: "UUID",
      Serie: "Serie",
      Folio: "Folio",
      RfcReceptor: "RFC receptor",
      NombreReceptor: "Receptor",
      TipoDeComprobante: "Tipo de comprobante",
      UsoCFDIReceptor: "Uso de CFDI",
      "c_forma_pago.code": "Forma de pago código",
      "c_forma_pago.name": "Forma de pago",
      MetodoPago: "Método de pago",
      SubTotalMXN: "Subtotal",
      DescuentoMXN: "Descuentos",
      NetoMXN: "Neto",
    },
    "EXCLUDED-PREFILLED-INCOMES": {
      Fecha: "Fecha expedición",
      UUID: "UUID",
      Serie: "Serie",
      Folio: "Folio",
      RfcEmisor: "RFC emisor",
      NombreEmisor: "Emisor",
      TipoDeComprobante: "Tipo de comprobante",
      UsoCFDIReceptor: "Uso de CFDI",
      "c_forma_pago.code": "Forma de pago código",
      "c_forma_pago.name": "Forma de pago",
      MetodoPago: "Método de pago",
      SubTotalMXN: "Subtotal",
      DescuentoMXN: "Descuentos",
      NetoMXN: "Neto",
      RetencionesISRMXN: "Retenciones ISR",
    },
    "EXCLUDED-PREFILLED-PAYMENT": {
      FechaPago: "Fecha de pago",
      "cfdi_origin.Fecha": "Fecha de emisión",
      UUID: "UUID",
      Serie: "Serie",
      Folio: "Folio",
      "cfdi_origin.RfcEmisor": "RFC emisor",
      "cfdi_origin.NombreEmisor": "Emisor",
      "payment_related.FormaDePagoP": "Forma de pago código",
      "payment_related.c_forma_pago.name": "Forma de pago",
      "cfdi_related.Serie": "DR - Serie",
      "cfdi_related.Folio": "DR - Folio",
      "cfdi_related.Fecha": "DR - Fecha de emisión",
      UUID_related: "DR - UUID",
      "cfdi_related.MetodoPago": "DR - Método de pago",
      "cfdi_related.UsoCFDIReceptor": "DR - Uso de CFDI",
      ObjetoImpDR: "DR - Objeto de impuesto",
      BaseIVA16: "DR - Base IVA 16%",
      BaseIVA8: "DR - Base IVA 8%",
      BaseIVA0: "DR - Base IVA 0%",
      BaseIVAExento: "DR - Base IVA Exento",
      Neto: "DR - Neto",
      RetencionesISR: "DR - Retenciones ISR",
      ImpPagadoMXN: "DR - Importe pagado",
    },
    EGRESS: {
      Fecha: "Fecha expedición",
      UUID: "UUID",
      Serie: "Serie",
      Folio: "Folio",
      RfcEmisor: "RFC emisor",
      NombreEmisor: "Emisor",
      TipoDeComprobante: "Tipo de comprobante",
      UsoCFDIReceptor: "Uso de CFDI",
      "c_forma_pago.code": "Forma de pago código",
      "c_forma_pago.name": "Forma de pago",
      MetodoPago: "Método de pago",
      SubTotalMXN: "Subtotal",
      DescuentoMXN: "Descuentos",
      NetoMXN: "Neto",
      RetencionesISRMXN: "Retenciones ISR",
    },
    INVESTMENTS: {
      Fecha: "Fecha expedición",
      UUID: "UUID",
      Serie: "Serie",
      Folio: "Folio",
      RfcEmisor: "RFC emisor",
      NombreEmisor: "Emisor",
      TipoDeComprobante: "Tipo de comprobante",
      UsoCFDIReceptor: "Uso de CFDI",
      "c_uso_cfdi.name": "Uso de CFDI descripción",
      "c_forma_pago.code": "Forma de pago código",
      "c_forma_pago.name": "Forma de pago",
      MetodoPago: "Método de pago",
      SubTotalMXN: "Subtotal",
      DescuentoMXN: "Descuentos",
      NetoMXN: "Neto",
    },
    // No considerados ISR
    "EXCLUDED-CASH": {
      Fecha: "Fecha expedición",
      UUID: "UUID",
      Serie: "Serie",
      Folio: "Folio",
      RfcEmisor: "RFC emisor",
      NombreEmisor: "Emisor",
      TipoDeComprobante: "Tipo de comprobante",
      UsoCFDIReceptor: "Uso de CFDI",
      "c_forma_pago.code": "Forma de pago código",
      "c_forma_pago.name": "Forma de pago",
      MetodoPago: "Método de pago",
      SubTotalMXN: "Subtotal",
      DescuentoMXN: "Descuentos",
      NetoMXN: "Neto",
      RetencionesISRMXN: "Retenciones ISR",
    },
    "EXCLUDED-EXCLUDED-INCOMES": {
      Fecha: "Fecha expedición",
      UUID: "UUID",
      Serie: "Serie",
      Folio: "Folio",
      RfcReceptor: "RFC receptor",
      NombreReceptor: "Receptor",
      TipoDeComprobante: "Tipo de comprobante",
      UsoCFDIReceptor: "Uso de CFDI",
      "c_forma_pago.code": "Forma de pago código",
      "c_forma_pago.name": "Forma de pago",
      MetodoPago: "Método de pago",
      SubTotalMXN: "Subtotal",
      DescuentoMXN: "Descuentos",
      NetoMXN: "Neto",
    },
    "EXCLUDED-EXCLUDED-EGRESS": {
      Fecha: "Fecha expedición",
      UUID: "UUID",
      Serie: "Serie",
      Folio: "Folio",
      RfcReceptor: "RFC receptor",
      NombreReceptor: "Receptor",
      TipoDeComprobante: "Tipo de comprobante",
      UsoCFDIReceptor: "Uso de CFDI",
      "c_forma_pago.code": "Forma de pago código",
      "c_forma_pago.name": "Forma de pago",
      MetodoPago: "Método de pago",
      SubTotalMXN: "Subtotal",
      DescuentoMXN: "Descuentos",
      NetoMXN: "Neto",
    },
    "EXCLUDED-EXCLUDED-INCOMES-PUE": {
      Fecha: "Fecha expedición",
      UUID: "UUID",
      Serie: "Serie",
      Folio: "Folio",
      RfcEmisor: "RFC emisor",
      NombreEmisor: "Emisor",
      TipoDeComprobante: "Tipo de comprobante",
      UsoCFDIReceptor: "Uso de CFDI",
      "c_forma_pago.code": "Forma de pago código",
      "c_forma_pago.name": "Forma de pago",
      MetodoPago: "Método de pago",
      SubTotalMXN: "Subtotal",
      DescuentoMXN: "Descuentos",
      NetoMXN: "Neto",
      RetencionesISRMXN: "Retenciones ISR",
    },
    "EXCLUDED-EGRESS": {
      Fecha: "Fecha expedición",
      UUID: "UUID",
      Serie: "Serie",
      Folio: "Folio",
      RfcEmisor: "RFC emisor",
      NombreEmisor: "Emisor",
      TipoDeComprobante: "Tipo de comprobante",
      UsoCFDIReceptor: "Uso de CFDI",
      "c_forma_pago.code": "Forma de pago código",
      "c_forma_pago.name": "Forma de pago",
      MetodoPago: "Método de pago",
      SubTotalMXN: "Subtotal",
      DescuentoMXN: "Descuentos",
      NetoMXN: "Neto",
      RetencionesISRMXN: "Retenciones ISR",
    },
    // No considerados ISR
    PAYMENT: {
      FechaPago: "Fecha de pago",
      "cfdi_origin.Fecha": "Fecha de emisión",
      UUID: "UUID",
      Serie: "Serie",
      Folio: "Folio",
      "cfdi_origin.RfcEmisor": "RFC emisor",
      "cfdi_origin.NombreEmisor": "Emisor",
      "payment_related.FormaDePagoP": "Forma de pago código",
      "payment_related.c_forma_pago.name": "Forma de pago",
      "cfdi_related.Serie": "DR - Serie",
      "cfdi_related.Folio": "DR - Folio",
      "cfdi_related.Fecha": "DR - Fecha de emisión",
      UUID_related: "DR - UUID",
      "cfdi_related.MetodoPago": "DR - Método de pago",
      "cfdi_related.UsoCFDIReceptor": "DR - Uso de CFDI",
      ObjetoImpDR: "DR - Objeto de impuesto",
      BaseIVA16: "DR - Base IVA 16%",
      BaseIVA8: "DR - Base IVA 8%",
      BaseIVA0: "DR - Base IVA 0%",
      BaseIVAExento: "DR - Base IVA Exento",
      Neto: "DR - Neto",
      RetencionesISR: "DR - Retenciones ISR",
      ImpPagadoMXN: "DR - Importe pagado",
    },
    "EXCLUDED-PREFILLED-EXCLUDED-PREFILLED-PAYMENT": {
      // "cfdi_origin.ExcludeFromISR": "No considerar ISR",
      FechaPago: "Fecha de pago",
      "cfdi_origin.Fecha": "Fecha de emisión",
      UUID: "UUID",
      Serie: "Serie",
      Folio: "Folio",
      "cfdi_origin.RfcEmisor": "RFC emisor",
      "cfdi_origin.NombreEmisor": "Emisor",
      "payment_related.FormaDePagoP": "Forma de pago código",
      "payment_related.c_forma_pago.name": "Forma de pago",
      "cfdi_related.Serie": "DR - Serie",
      "cfdi_related.Folio": "DR - Folio",
      "cfdi_related.Fecha": "DR - Fecha de emisión",
      UUID_related: "DR - UUID",
      "cfdi_related.MetodoPago": "DR - Método de pago",
      "cfdi_related.UsoCFDIReceptor": "DR - Uso de CFDI",
      ObjetoImpDR: "DR - Objeto de impuesto",
      BaseIVA16: "DR - Base IVA 16%",
      BaseIVA8: "DR - Base IVA 8%",
      BaseIVA0: "DR - Base IVA 0%",
      BaseIVAExento: "DR - Base IVA Exento",
      Neto: "DR - Neto",
      RetencionesISR: "DR - Retenciones ISR",
      ImpPagadoMXN: "DR - Importe pagado",
    },
    "EXCLUDED-PAYMENT": {
      // "cfdi_origin.ExcludeFromISR": "No considerar ISR",
      FechaPago: "Fecha de pago",
      "cfdi_origin.Fecha": "Fecha de emisión",
      UUID: "UUID",
      Serie: "Serie",
      Folio: "Folio",
      "cfdi_origin.RfcEmisor": "RFC emisor",
      "cfdi_origin.NombreEmisor": "Emisor",
      "payment_related.FormaDePagoP": "Forma de pago código",
      "payment_related.c_forma_pago.name": "Forma de pago",
      "cfdi_related.Serie": "DR - Serie",
      "cfdi_related.Folio": "DR - Folio",
      "cfdi_related.Fecha": "DR - Fecha de emisión",
      UUID_related: "DR - UUID",
      "cfdi_related.MetodoPago": "DR - Método de pago",
      "cfdi_related.UsoCFDIReceptor": "DR - Uso de CFDI",
      ObjetoImpDR: "DR - Objeto de impuesto",
      BaseIVA16: "DR - Base IVA 16%",
      BaseIVA8: "DR - Base IVA 8%",
      BaseIVA0: "DR - Base IVA 0%",
      BaseIVAExento: "DR - Base IVA Exento",
      Neto: "DR - Neto",
      RetencionesISR: "DR - Retenciones ISR",
      ImpPagadoMXN: "DR - Importe pagado",
    },
    "EXCLUDED-EXCLUDED-PAYMENTS": {
      // "cfdi_origin.ExcludeFromISR": "No considerar ISR",
      FechaPago: "Fecha de pago",
      "cfdi_origin.Fecha": "Fecha de emisión",
      UUID: "UUID",
      Serie: "Serie",
      Folio: "Folio",
      "cfdi_origin.RfcEmisor": "RFC emisor",
      "cfdi_origin.NombreEmisor": "Emisor",
      "payment_related.FormaDePagoP": "Forma de pago código",
      "payment_related.c_forma_pago.name": "Forma de pago",
      "cfdi_related.Serie": "DR - Serie",
      "cfdi_related.Folio": "DR - Folio",
      "cfdi_related.Fecha": "DR - Fecha de emisión",
      UUID_related: "DR - UUID",
      "cfdi_related.MetodoPago": "DR - Método de pago",
      "cfdi_related.UsoCFDIReceptor": "DR - Uso de CFDI",
      ObjetoImpDR: "DR - Objeto de impuesto",
      BaseIVA16: "DR - Base IVA 16%",
      BaseIVA8: "DR - Base IVA 8%",
      BaseIVA0: "DR - Base IVA 0%",
      BaseIVAExento: "DR - Base IVA Exento",
      Neto: "DR - Neto",
      RetencionesISR: "DR - Retenciones ISR",
      ImpPagadoMXN: "DR - Importe pagado",
    },
  };

  return COMMON_COLUMNS[switchTab];
}
