const COMMON_FIELDS: string[] = [
  "FechaCancelacion",
  "from_xml",
  "Serie",
  "Folio",
  "TipoDeComprobante",
  "c_tipo_de_comprobante.name",
  "PaymentDate",
  "ExcludeFromIVA",
  "ExcludeFromISR",
  "Fecha",
  "UUID",
  "NombreEmisor",
  "RfcEmisor",
  "LugarExpedicion",
  "RegimenFiscalEmisor",
  "c_regimen_fiscal_emisor.name",
  "RegimenFiscalReceptor",
  "c_regimen_fiscal_receptor.name",
  "DomicilioFiscalReceptor",
  "NombreReceptor",
  "RfcReceptor",
  "NoCertificado",
  "Moneda",
  "c_moneda.name",
  "FormaPago",
  "c_forma_pago.name",
  "MetodoPago",
  "c_metodo_pago.name",
  "UsoCFDIReceptor",
  "c_uso_cfdi.name",
  "Version",
  "Conceptos",
  "SubTotal",
  "Total",
  "Descuento",
  "TrasladosIEPS",
  "TrasladosISR",
  "TrasladosIVA",
  "RetencionesIEPS",
  "RetencionesISR",
  "RetencionesIVA",
  // "company_identifier",
  "Estatus",
  "is_issued",
];

const INGRESS_FIELDS: string[] = [];

const EGRESS_FIELDS: string[] = [
  "cfdi_related.uuid_origin",
  "cfdi_related.Estatus",
  "cfdi_related.TipoRelacion",
  "cfdi_related.TipoDeComprobante",
  "cfdi_origin.uuid_related",
  "cfdi_origin.cfdi_related.UUID",
  "cfdi_origin.cfdi_related.TipoDeComprobante",
  "cfdi_origin.cfdi_related.Estatus",
  "cfdi_origin.TipoRelacion",
];

const TRANSFER_FIELDS: string[] = [];

const PAYROLL_FIELDS: string[] = [
  "FechaFiltro",
  "nomina.ReceptorTipoRegimen",
  "nomina.TotalPercepciones",
  "nomina.TotalDeducciones",
  "nomina.TotalOtrosPagos",
  "nomina.PercepcionesTotalSueldos",
  "nomina.OtrasPercepciones",
  "nomina.PercepcionesTotalGravado",
  "nomina.PercepcionesTotalExento",
  "nomina.AjusteISRRetenido",
  "nomina.DeduccionesTotalImpuestosRetenidos",
  "nomina.DeduccionesTotalOtrasDeducciones",
  "nomina.SubsidioCausado",
  "nomina.NetoAPagar",
  "nomina.Version",
  "nomina.TipoNomina",
  "nomina.FechaInicialPago",
  "nomina.FechaFinalPago",
  "nomina.NumDiasPagados",
  "nomina.EmisorRegistroPatronal",
  "nomina.ReceptorCurp",
  "nomina.ReceptorNumSeguridadSocial",
  "nomina.ReceptorFechaInicioRelLaboral",
  "nomina.ReceptorAntigüedad",
  "nomina.ReceptorTipoContrato",
  "nomina.ReceptorSindicalizado",
  "nomina.ReceptorTipoJornada",
  "nomina.ReceptorNumEmpleado",
  "nomina.ReceptorDepartamento",
  "nomina.ReceptorPuesto",
  "nomina.ReceptorRiesgoPuesto",
  "nomina.ReceptorPeriodicidadPago",
  "nomina.ReceptorBanco",
  "nomina.ReceptorCuentaBancaria",
  "nomina.ReceptorSalarioBaseCotApor",
  "nomina.ReceptorSalarioDiarioIntegrado",
  "nomina.ReceptorClaveEntFed",
  "Sello",
  "nomina.PercepcionesSeparacionIndemnizacion",
  "nomina.PercepcionesJubilacionPensionRetiro",
  "nomina.FechaPago",
  "nomina.c_ReceptorPeriodicidadPago.name",
  "DomicilioFiscalReceptor",
  "CfdiRelacionados",
  "is_too_big",
];

const PAYMENT_FIELDS: string[] = [
  "payments.FechaPago",
  "payments.NumOperacion",
  "payments.NomBancoOrdExt",
  "payments.RfcEmisorCtaOrd",
  "payments.CtaOrdenante",
  "payments.RfcEmisorCtaBen",
  "payments.CtaBeneficiario",
  "payments.MonedaP",
  "payments.TipoCambioP",
  "payments.c_forma_pago.name",
  "pays.UUID_related",
  "pays.Folio",
  "pays.MonedaDR",
  "pays.MetodoDePagoDR",
  "pays.NumParcialidad",
  "pays.ImpSaldoAnt",
  "pays.ImpPagado",
  "pays.ImpSaldoInsoluto",
  "pays.cfdi_related.MetodoPago",
  "pays.ObjetoImpDR",
  "is_issued",
  "pr_count",
];

export const fieldsPerType = {
  I: [...COMMON_FIELDS, ...INGRESS_FIELDS],
  E: [...COMMON_FIELDS, ...EGRESS_FIELDS],
  T: [...COMMON_FIELDS, ...TRANSFER_FIELDS],
  N: [...COMMON_FIELDS, ...PAYROLL_FIELDS],
  P: [...COMMON_FIELDS, ...PAYMENT_FIELDS],
};
