import { ColumnsType } from "antd/lib/table";
import { DisplayType, formatDisplay } from "../formatDisplay";

const payrollTotalColumns: ColumnsType<PayrollTotalsTypeWithKey> = [
  { title: "Tipo", dataIndex: "type", key: "type", fixed: "left", width: 100 },
  {
    title: "Conteo de CFDIs",
    dataIndex: "Qty",
    key: "Qty",
    width: 125,
  },
  {
    title: "Número de empleados",
    dataIndex: "EmpleadosQty",
    key: "EmpleadosQty",
    render: (val) => val,
    align: "right",
    width: 175,
  },
  {
    title: "Percepciones",
    dataIndex: "TotalPercepciones",
    key: "TotalPercepciones",
    render: (val) => formatDisplay(val, DisplayType.MONEY),
    align: "right",
    width: 155,
  },
  {
    title: "Otras percepciones",
    dataIndex: "OtrasPercepciones",
    key: "OtrasPercepciones",
    render: (val) => formatDisplay(val, DisplayType.MONEY),
    align: "right",
    width: 155,
  },
  {
    title: "Separación-Indemnización",
    dataIndex: "PercepcionesSeparacionIndemnizacion",
    key: "PercepcionesSeparacionIndemnizacion",
    render: (val) => formatDisplay(val, DisplayType.MONEY),
    align: "right",
    width: 220,
  },
  {
    title: "Jubilación-Pensión",
    dataIndex: "PercepcionesJubilacionPensionRetiro",
    key: "PercepcionesJubilacionPensionRetiro",
    render: (val) => formatDisplay(val, DisplayType.MONEY),
    align: "right",
    width: 150,
  },
  {
    title: "Deducciones",
    dataIndex: "TotalDeducciones",
    key: "TotalDeducciones",
    render: (val) => formatDisplay(val, DisplayType.MONEY),
    align: "right",
    width: 125,
  },
  {
    title: "Otros pagos",
    dataIndex: "TotalOtrosPagos",
    key: "TotalOtrosPagos",
    render: (val) => formatDisplay(val, DisplayType.MONEY),
    align: "right",
    width: 125,
  },
  {
    title: "Sueldo",
    dataIndex: "PercepcionesTotalSueldos",
    key: "PercepcionesTotalSueldos",
    render: (val) => formatDisplay(val, DisplayType.MONEY),
    align: "right",
    width: 155,
  },
  {
    title: "Gravado",
    dataIndex: "PercepcionesTotalGravado",
    key: "PercepcionesTotalGravado",
    render: (val) => formatDisplay(val, DisplayType.MONEY),
    align: "right",
    width: 155,
  },
  {
    title: "Exento",
    dataIndex: "PercepcionesTotalExento",
    key: "PercepcionesTotalExento",
    render: (val) => formatDisplay(val, DisplayType.MONEY),
    align: "right",
    width: 150,
  },
  {
    title: "ISR retenido",
    dataIndex: "DeduccionesTotalImpuestosRetenidos",
    key: "DeduccionesTotalImpuestosRetenidos",
    render: (val) => formatDisplay(val, DisplayType.MONEY),
    align: "right",
    width: 160,
  },
  {
    title: "Ajuste ISR retenido",
    dataIndex: "DeduccionesTotalImpuestosRetenidos",
    key: "DeduccionesTotalImpuestosRetenidos",
    render: (val) => formatDisplay(val, DisplayType.MONEY),
    align: "right",
    width: 160,
  },
  {
    title: "Otras deducciones",
    dataIndex: "DeduccionesTotalOtrasDeducciones",
    key: "DeduccionesTotalOtrasDeducciones",
    render: (val) => formatDisplay(val, DisplayType.MONEY),
    align: "right",
    width: 160,
  },
  {
    title: "Ajuste ISR retenido",
    dataIndex: "AjusteISRRetenido",
    key: "AjusteISRRetenido",
    render: (val) => formatDisplay(val, DisplayType.MONEY),
    align: "right",
    width: 160,
  },
  {
    title: "Subsidio causado",
    dataIndex: "SubsidioCausado",
    key: "SubsidioCausado",
    render: (val) => formatDisplay(val, DisplayType.MONEY),
    align: "right",
    width: 150,
  },
  {
    title: "Neto a pagar",
    dataIndex: "NetoAPagar",
    key: "NetoAPagar",
    render: (val) => formatDisplay(val, DisplayType.MONEY),
    align: "right",
    width: 150,
  },
  {
    title: "Separación-Indemnización",
    dataIndex: "PercepcionesSeparacionIndemnizacion",
    key: "PercepcionesSeparacionIndemnizacion",
    render: (val) => formatDisplay(val, DisplayType.MONEY),
    align: "right",
    width: 150,
  },
];

export default payrollTotalColumns;
